#!/bin/bash
kill $(ps aux | grep '[p]ython test_viff.py' | awk '{print $2}')
kill $(ps aux | grep '[p]ython test_viff_pure.py' | awk '{print $2}')
kill $(ps aux | grep '[p]ython test_mpc_naive.py' | awk '{print $2}')
